services:
  unturned:
    build: .
    container_name: unturned
    tty: true
    stdin_open: true
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
    volumes:
      - unturned:/home/steam/Unturned
    environment:
      - SERVER_NAME=server
      - OPENMOD_INSTALL=true
      - ROCKETMOD_INSTALL=true
volumes:
  unturned: